In [2]:
import pandas as pd

df = pd.read_csv('D600 Task 3 Dataset 1 Housing Information.csv')

df.head(10)

,ID,Price,SquareFootage,NumBathrooms,NumBedrooms,BackyardSpace,CrimeRate,SchoolRating,AgeOfHome,DistanceToCityCenter,...,RenovationQuality,LocalAmenities,TransportAccess,Fireplace,HouseColor,Garage,Floors,Windows,PreviousSalePrice,IsLuxury
0,4922,255614.8992,566.62,1.000000,4,779.42,20.56,5.62,39.46,10.08,...,4.93,4.44,4.55,Yes,Blue,No,1,13,181861.54230,0
1,5009,155586.0947,1472.34,1.000000,2,656.13,15.62,5.63,40.51,7.89,...,4.08,5.56,6.83,No,Green,No,1,17,50042.59757,0
2,4450,131050.8324,550.00,1.779354,3,754.57,12.47,9.20,48.38,23.74,...,4.26,8.07,8.48,Yes,Green,Yes,2,34,48400.34440,0
3,1070,151361.7125,941.81,2.035254,2,439.59,22.22,7.08,94.67,5.22,...,4.45,5.00,6.27,Yes,Red,No,1,14,84594.12145,0
4,400,113167.6128,550.00,1.064644,3,353.03,8.28,5.93,16.80,43.13,...,3.36,5.46,6.99,No,White,Yes,1,21,22934.59654,0
5,5979,224973.4118,1474.99,1.857532,2,774.45,25.39,4.92,57.62,19.71,...,6.15,0.98,1.90,No,White,Yes,2,36,160664.13150,0
6,3703,169471.5239,1069.49,1.230458,3,757.58,37.84,4.40,46.86,5.73,...,5.82,4.25,5.12,No,White,No,1,10,89824.60649,0
7,2260,265497.8918,550.00,1.000000,1,636.64,48.26,4.32,60.29,11.35,...,5.81,5.43,6.03,No,Yellow,Yes,1,15,177283.19610,0
8,6739,146559.7638,550.00,1.000000,4,603.68,5.03,5.78,104.34,42.05,...,3.54,7.12,6.40,No,Red,Yes,1,19,53649.98602,0
9,2469,148126.1958,983.26,1.000000,2,206.33,24.37,5.18,50.91,31.04,...,7.19,9.72,9.73,No,Red,Yes,1,9,177535.54750,0